### ISSUE TITLE
Tag -> Deployment causes: validation failed: github release plugin is only available for tags

### ISSUE THREAD

**Issue by s00500** [woodpecker-ci/plugin-github-release#7]
I have a tag triggereing a pipeline, afterwards I want to deploy said pipeline but I stumble across this validation error... should this be removed for that case ?

**Comment by 6543** [comment]
https://github.com/woodpecker-ci/plugin-github-release/blob/7618faee14f88ce6b3caa33158e472b62e96ae6a/plugin/impl.go#L47-L49

can you confirm it would work if we alter that specific case?

if so we should document this and might add a setting for this plugin?

**Comment by s00500** [comment]
Yes and Yes, sorry I did not come back to that earlier, thanks for closing
